### ISSUE TITLE
Destroy on expired preauth key failing 

### ISSUE THREAD

**Issue by samson4649** [awlsring/terraform-provider-headscale#1]
### Issue
When attempting to delete a preauthentication key, via a destroy process, which has already expired an error is thrown. 

![image](https://github.com/awlsring/terraform-provider-headscale/assets/12725953/9c8588ca-81d4-4749-b522-f1a6d4585237)

The headscale server doesnt provide a way to delete preauth keys from the API, instead keys are expired. As such, the key is already in the intended state (expired). 

https://github.com/awlsring/terraform-provider-headscale/blob/64a356170b3560eae049c5fa191e3b6f5e16ab92/headscale/preauthkey/resource.go#L251-L254

### Temp Fix
As the error returned from the headscale client doesnt provide an easy way to assess if the error was thrown due to key expiry, a string comparison ([fork](https://github.com/samson4649/terraform-provider-headscale/blob/8f4e4c8d60f4bb2d7bbdcec4bc2de34243108fac/headscale/preauthkey/resource.go#L252-L255)). The following could be used to check the output of `err.Error()` against this condition as demonstrated below:

```diff
  func (r *preAuthKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	  var state preAuthKeyResourceModel
	  diags := req.State.Get(ctx, &state)
	  resp.Diagnostics.Append(diags...)
	  if resp.Diagnostics.HasError() {
		  return
	  }
  
	  err := r.client.ExpirePreAuthKey(ctx, state.User.ValueString(), state.Key.ValueString())
	  if err != nil {
+		  e := err.Error()
+		  if strings.Contains(e, "&{Code:2 Details:[] Message:AuthKey expired}") {
+			  return
+		  }
		  resp.Diagnostics.AddError(
			  "Error deleting pre auth key",
			  "Could not expire key, unexpected error: "+err.Error(),
		  )
		  return
	  }
  }
```

### Ideal FIx
Being able to get responses back from the headscale client which allow access to the headscale server reponse code (not status code). This can then be used to properly act on the response.

**Comment by awlsring** [comment]
Hey thanks for looking into this!

I started playing around to see what changes that could be implemented here to get towards the ideal fix you proposed. It seems when the PreAuthKey is expired, the status code is 500 and the response code is 2. Unfortunately this is the same response you get if you make a request targeting an invalid authkey, so with the current API im not sure if there is a way to do this cleanly.

The fix I'm going to implement is similar to what your temp fix does, but moves it into the internal client. The method used by the provider now does the following

```
func (h *HeadscaleService) ExpirePreAuthKey(ctx context.Context, user string, key string) error {
	request := headscale_service.NewHeadscaleServiceExpirePreAuthKeyParams()
	request.SetContext(ctx)
	request.SetBody(&models.V1ExpirePreAuthKeyRequest{
		User: user,
		Key:  key,
	})

	_, err := h.client.HeadscaleService.HeadscaleServiceExpirePreAuthKey(request)
	if err != nil {
		if e, ok := err.(*headscale_service.HeadscaleServiceExpirePreAuthKeyDefault); ok { // Get ErrorCode info
			if strings.Contains(e.Payload.Message, "AuthKey expired") { // Grossly check if it matches the error we expect and return no error if so
				return nil
			}
		}
		return err
	}
	return nil
}
```
