### ISSUE TITLE
too strict tags validator

### ISSUE THREAD

**Issue by paragor** [awlsring/terraform-provider-headscale#6]
in headscale_device_tags (Resource) there is too strict regexp for tag
```
stringvalidator.RegexMatches(regexp.MustCompile("^tag:[\\w\\d]+$"), "tag must follow scheme of `tag:<value>`"),
```

it is not allowed use tag "tag:location:sgp1", because it have `:`, that not \w and not \d

headscale allow to use that tags

**Comment by awlsring** [comment]
Yeah after some playing around, it seems like a tag can be of almost any length and any unicode character so this regex should be `^tag:.*`. 

I'll cut a fix for this sometime soon.
