### ISSUE TITLE
Compatibility with headscale 0.23.0

### ISSUE THREAD

**Issue by oneingan** [awlsring/terraform-provider-headscale#7]
The recently released headscale version 0.23.0 introduces some breaking changes that affect compatibility with the current terraform-provider-headscale implementation. It would be great to have the provider updated to support this version.

https://github.com/juanfont/headscale/releases/tag/v0.23.0

Thanks for your hard work on this project!

**Comment by awlsring** [comment]
Oh awesome! I plan on adding support for this. I am pretty busy at work so I won't be able to address this for a bit. But it will happen!

**Comment by awlsring** [comment]
I've started working on this. I believe I made the changes needed to support this. Before publishing, I need to read up on how I can manage these version on the registry.

**Comment by oneingan** [comment]
let me know if you need some help on testing changes

**Comment by awlsring** [comment]
Just pushed v0.2.0 with support for this.
